### ISSUE TITLE
After Upgrade from Cortex 1.0.2 to 1.1.1 system does not come up

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/Cortex#26]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| Cortex version / git hash   |1.1.1
| Package Type              | Debian Package

### Problem Description
After Upgrade Cortex does not come up.
It Looks as anything was missing (maybe in the config?)

Error Messages:
```
2017-05-19 09:54:56,987 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-2 - Slf4jLogger started
2017-05-19 09:54:58,701 [ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-3 - Unable to provision, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: None.get
  at services.MispSrv.<init>(MispSrv.scala:32)
  at services.MispSrv.class(MispSrv.scala:21)
  while locating services.MispSrv
    for parameter 1 at services.AnalyzerSrv.<init>(AnalyzerSrv.scala:12)
  at services.AnalyzerSrv.class(AnalyzerSrv.scala:12)
  while locating services.AnalyzerSrv
    for parameter 1 at services.JobActor.<init>(JobSrv.scala:109)
  while locating services.JobActor

1 error
akka.actor.ActorInitializationException: akka://application/user/JobActor: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
        at akka.actor.ActorCell.create(ActorCell.scala:607)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: None.get
  at services.MispSrv.<init>(MispSrv.scala:32)
  at services.MispSrv.class(MispSrv.scala:21)
  while locating services.MispSrv
    for parameter 1 at services.AnalyzerSrv.<init>(AnalyzerSrv.scala:12)
  at services.AnalyzerSrv.class(AnalyzerSrv.scala:12)
  while locating services.AnalyzerSrv
    for parameter 1 at services.JobActor.<init>(JobSrv.scala:109)
  while locating services.JobActor

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:405)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:400)
        at play.api.libs.concurrent.ActorRefProvider$$anonfun$1.apply(Akka.scala:210)
        at play.api.libs.concurrent.ActorRefProvider$$anonfun$1.apply(Akka.scala:210)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:562)
        at akka.actor.ActorCell.create(ActorCell.scala:588)
        ... 9 common frames omitted
Caused by: java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at services.MispSrv.<init>(MispSrv.scala:34)
        at services.MispSrv$$FastClassByGuice$$52b14c8e.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        ... 18 common frames omitted

```

Configuration:

```
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
http.port=9001
play.crypto.secret="XXXXXXXXXXXXXXXXXXX"
analyzer {
  path = "/opt/Cortex-Analyzers/analyzers"
config {
    global {
      proxy {
        http="http://x:8080",
        https="http://y:8080"
      }
    }
    DNSDB {
      server="https://api.dnsdb.info"
      key="..."
    }
    DomainTools {
      username="..."
      key="..."
    }
[...]
    PassiveTotal {
      key="..."
      username=".."
    }
    MISP {
            url="https://misp.local.dom"
            key="..."
            certpath=["/etc/ssl/private/misp.local.crt", ""]
            name="instance-1"
}
  }
}

```

**Comment by To-om** [comment]
This error means that configuration is missing. I haven't identified yet why you have this problem. The package should contain default configuration file (reference.conf).

As workaround, you can add the following line in your application.conf:
```
misp.modules.loader = ${play.server.dir}/"contrib/misp-modules-loader.py"
```

**Comment by To-om** [comment]
I've published a new debian package which fix this problem.
